apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karo.fullname" . }}-operator
  namespace: {{ include "karo.namespace" . }}
  labels:
    {{- include "karo.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "karo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "karo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: {{ include "karo.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:{{ .Values.observability.metrics.port | default 8080 }}
            {{- end }}
            - --health-probe-bind-address=:8081
            {{- if .Values.webhook.enabled }}
            - --webhook-port=9443
            {{- end }}
          ports:
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.observability.metrics.port | default 8080 }}
              protocol: TCP
            {{- end }}
            - name: health
              containerPort: 8081
              protocol: TCP
            {{- if .Values.webhook.enabled }}
            - name: webhook
              containerPort: 9443
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.webhook.enabled }}
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          {{- end }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: cert
          secret:
            secretName: {{ include "karo.fullname" . }}-webhook-cert
            defaultMode: 420
      {{- end }}
