//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCapability) DeepCopyInto(out *AgentCapability) {
	*out = *in
	if in.SkillPrompt != nil {
		in, out := &in.SkillPrompt, &out.SkillPrompt
		*out = new(SystemPromptConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RequiredTools != nil {
		in, out := &in.RequiredTools, &out.RequiredTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCapability.
func (in *AgentCapability) DeepCopy() *AgentCapability {
	if in == nil {
		return nil
	}
	out := new(AgentCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannel) DeepCopyInto(out *AgentChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannel.
func (in *AgentChannel) DeepCopy() *AgentChannel {
	if in == nil {
		return nil
	}
	out := new(AgentChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelActiveTaskGraph) DeepCopyInto(out *AgentChannelActiveTaskGraph) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelActiveTaskGraph.
func (in *AgentChannelActiveTaskGraph) DeepCopy() *AgentChannelActiveTaskGraph {
	if in == nil {
		return nil
	}
	out := new(AgentChannelActiveTaskGraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelList) DeepCopyInto(out *AgentChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelList.
func (in *AgentChannelList) DeepCopy() *AgentChannelList {
	if in == nil {
		return nil
	}
	out := new(AgentChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelSpec) DeepCopyInto(out *AgentChannelSpec) {
	*out = *in
	in.Platform.DeepCopyInto(&out.Platform)
	in.Inbound.DeepCopyInto(&out.Inbound)
	in.Outbound.DeepCopyInto(&out.Outbound)
	out.Approvals = in.Approvals
	if in.TeamHandoff != nil {
		in, out := &in.TeamHandoff, &out.TeamHandoff
		*out = make([]TeamHandoffRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelSpec.
func (in *AgentChannelSpec) DeepCopy() *AgentChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AgentChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentChannelStatus) DeepCopyInto(out *AgentChannelStatus) {
	*out = *in
	if in.LastInboundMessageAt != nil {
		in, out := &in.LastInboundMessageAt, &out.LastInboundMessageAt
		*out = (*in).DeepCopy()
	}
	if in.LastOutboundMessageAt != nil {
		in, out := &in.LastOutboundMessageAt, &out.LastOutboundMessageAt
		*out = (*in).DeepCopy()
	}
	if in.ActiveTaskGraphs != nil {
		in, out := &in.ActiveTaskGraphs, &out.ActiveTaskGraphs
		*out = make([]AgentChannelActiveTaskGraph, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentChannelStatus.
func (in *AgentChannelStatus) DeepCopy() *AgentChannelStatus {
	if in == nil {
		return nil
	}
	out := new(AgentChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfigFile) DeepCopyInto(out *AgentConfigFile) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfigFile.
func (in *AgentConfigFile) DeepCopy() *AgentConfigFile {
	if in == nil {
		return nil
	}
	out := new(AgentConfigFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInstance) DeepCopyInto(out *AgentInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInstance.
func (in *AgentInstance) DeepCopy() *AgentInstance {
	if in == nil {
		return nil
	}
	out := new(AgentInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInstanceList) DeepCopyInto(out *AgentInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInstanceList.
func (in *AgentInstanceList) DeepCopy() *AgentInstanceList {
	if in == nil {
		return nil
	}
	out := new(AgentInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInstanceSpec) DeepCopyInto(out *AgentInstanceSpec) {
	*out = *in
	out.AgentSpecRef = in.AgentSpecRef
	if in.CurrentTaskRef != nil {
		in, out := &in.CurrentTaskRef, &out.CurrentTaskRef
		*out = new(TaskRef)
		**out = **in
	}
	out.Hibernation = in.Hibernation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInstanceSpec.
func (in *AgentInstanceSpec) DeepCopy() *AgentInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(AgentInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInstanceStatus) DeepCopyInto(out *AgentInstanceStatus) {
	*out = *in
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastActiveAt != nil {
		in, out := &in.LastActiveAt, &out.LastActiveAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInstanceStatus.
func (in *AgentInstanceStatus) DeepCopy() *AgentInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(AgentInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLoop) DeepCopyInto(out *AgentLoop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLoop.
func (in *AgentLoop) DeepCopy() *AgentLoop {
	if in == nil {
		return nil
	}
	out := new(AgentLoop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentLoop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLoopList) DeepCopyInto(out *AgentLoopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentLoop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLoopList.
func (in *AgentLoopList) DeepCopy() *AgentLoopList {
	if in == nil {
		return nil
	}
	out := new(AgentLoopList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentLoopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLoopSpec) DeepCopyInto(out *AgentLoopSpec) {
	*out = *in
	out.AgentSpecRef = in.AgentSpecRef
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]LoopTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoopPrompt != nil {
		in, out := &in.LoopPrompt, &out.LoopPrompt
		*out = new(SystemPromptConfig)
		(*in).DeepCopyInto(*out)
	}
	out.DispatcherRef = in.DispatcherRef
	if in.EvalGate != nil {
		in, out := &in.EvalGate, &out.EvalGate
		*out = new(LoopEvalGate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLoopSpec.
func (in *AgentLoopSpec) DeepCopy() *AgentLoopSpec {
	if in == nil {
		return nil
	}
	out := new(AgentLoopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLoopStatus) DeepCopyInto(out *AgentLoopStatus) {
	*out = *in
	if in.LastRunAt != nil {
		in, out := &in.LastRunAt, &out.LastRunAt
		*out = (*in).DeepCopy()
	}
	if in.NextRunAt != nil {
		in, out := &in.NextRunAt, &out.NextRunAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLoopStatus.
func (in *AgentLoopStatus) DeepCopy() *AgentLoopStatus {
	if in == nil {
		return nil
	}
	out := new(AgentLoopStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMailbox) DeepCopyInto(out *AgentMailbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMailbox.
func (in *AgentMailbox) DeepCopy() *AgentMailbox {
	if in == nil {
		return nil
	}
	out := new(AgentMailbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentMailbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMailboxList) DeepCopyInto(out *AgentMailboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentMailbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMailboxList.
func (in *AgentMailboxList) DeepCopy() *AgentMailboxList {
	if in == nil {
		return nil
	}
	out := new(AgentMailboxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentMailboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMailboxSpec) DeepCopyInto(out *AgentMailboxSpec) {
	*out = *in
	out.AgentSpecRef = in.AgentSpecRef
	if in.AcceptedMessageTypes != nil {
		in, out := &in.AcceptedMessageTypes, &out.AcceptedMessageTypes
		*out = make([]MessageType, len(*in))
		copy(*out, *in)
	}
	out.Delivery = in.Delivery
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMailboxSpec.
func (in *AgentMailboxSpec) DeepCopy() *AgentMailboxSpec {
	if in == nil {
		return nil
	}
	out := new(AgentMailboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMailboxStatus) DeepCopyInto(out *AgentMailboxStatus) {
	*out = *in
	if in.PendingMessages != nil {
		in, out := &in.PendingMessages, &out.PendingMessages
		*out = make([]MailboxMessage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OldestPendingMessage != nil {
		in, out := &in.OldestPendingMessage, &out.OldestPendingMessage
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMailboxStatus.
func (in *AgentMailboxStatus) DeepCopy() *AgentMailboxStatus {
	if in == nil {
		return nil
	}
	out := new(AgentMailboxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicy) DeepCopyInto(out *AgentPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicy.
func (in *AgentPolicy) DeepCopy() *AgentPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicyList) DeepCopyInto(out *AgentPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicyList.
func (in *AgentPolicyList) DeepCopy() *AgentPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicySpec) DeepCopyInto(out *AgentPolicySpec) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	in.Models.DeepCopyInto(&out.Models)
	out.ToolCalls = in.ToolCalls
	out.Loop = in.Loop
	in.TaskGraph.DeepCopyInto(&out.TaskGraph)
	out.Audit = in.Audit
	in.DataClassification.DeepCopyInto(&out.DataClassification)
	out.Escalation = in.Escalation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicySpec.
func (in *AgentPolicySpec) DeepCopy() *AgentPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPolicyStatus) DeepCopyInto(out *AgentPolicyStatus) {
	*out = *in
	if in.LastEvaluatedAt != nil {
		in, out := &in.LastEvaluatedAt, &out.LastEvaluatedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPolicyStatus.
func (in *AgentPolicyStatus) DeepCopy() *AgentPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AgentPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentScaling) DeepCopyInto(out *AgentScaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentScaling.
func (in *AgentScaling) DeepCopy() *AgentScaling {
	if in == nil {
		return nil
	}
	out := new(AgentScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpecList) DeepCopyInto(out *AgentSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpecList.
func (in *AgentSpecList) DeepCopy() *AgentSpecList {
	if in == nil {
		return nil
	}
	out := new(AgentSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpecSpec) DeepCopyInto(out *AgentSpecSpec) {
	*out = *in
	out.ModelConfigRef = in.ModelConfigRef
	in.SystemPrompt.DeepCopyInto(&out.SystemPrompt)
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]AgentCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AgentConfigFiles != nil {
		in, out := &in.AgentConfigFiles, &out.AgentConfigFiles
		*out = make([]AgentConfigFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MemoryRef != nil {
		in, out := &in.MemoryRef, &out.MemoryRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ToolSetRef != nil {
		in, out := &in.ToolSetRef, &out.ToolSetRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.SandboxClassRef != nil {
		in, out := &in.SandboxClassRef, &out.SandboxClassRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.WorkspaceCredentials != nil {
		in, out := &in.WorkspaceCredentials, &out.WorkspaceCredentials
		*out = new(WorkspaceCredentialsConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Runtime.DeepCopyInto(&out.Runtime)
	out.Scaling = in.Scaling
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpecSpec.
func (in *AgentSpecSpec) DeepCopy() *AgentSpecSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpecStatus) DeepCopyInto(out *AgentSpecStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpecStatus.
func (in *AgentSpecStatus) DeepCopy() *AgentSpecStatus {
	if in == nil {
		return nil
	}
	out := new(AgentSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTeam) DeepCopyInto(out *AgentTeam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTeam.
func (in *AgentTeam) DeepCopy() *AgentTeam {
	if in == nil {
		return nil
	}
	out := new(AgentTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTeam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTeamList) DeepCopyInto(out *AgentTeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentTeam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTeamList.
func (in *AgentTeamList) DeepCopy() *AgentTeamList {
	if in == nil {
		return nil
	}
	out := new(AgentTeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentTeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTeamMember) DeepCopyInto(out *AgentTeamMember) {
	*out = *in
	out.AgentSpecRef = in.AgentSpecRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTeamMember.
func (in *AgentTeamMember) DeepCopy() *AgentTeamMember {
	if in == nil {
		return nil
	}
	out := new(AgentTeamMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTeamSpec) DeepCopyInto(out *AgentTeamSpec) {
	*out = *in
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]AgentTeamMember, len(*in))
		copy(*out, *in)
	}
	in.SharedResources.DeepCopyInto(&out.SharedResources)
	out.DispatcherRef = in.DispatcherRef
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.LoopRef != nil {
		in, out := &in.LoopRef, &out.LoopRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTeamSpec.
func (in *AgentTeamSpec) DeepCopy() *AgentTeamSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTeamStatus) DeepCopyInto(out *AgentTeamStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTeamStatus.
func (in *AgentTeamStatus) DeepCopy() *AgentTeamStatus {
	if in == nil {
		return nil
	}
	out := new(AgentTeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalConfig) DeepCopyInto(out *ApprovalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalConfig.
func (in *ApprovalConfig) DeepCopy() *ApprovalConfig {
	if in == nil {
		return nil
	}
	out := new(ApprovalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Assertion) DeepCopyInto(out *Assertion) {
	*out = *in
	if in.JudgeModelConfigRef != nil {
		in, out := &in.JudgeModelConfigRef, &out.JudgeModelConfigRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Assertion.
func (in *Assertion) DeepCopy() *Assertion {
	if in == nil {
		return nil
	}
	out := new(Assertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditConfig) DeepCopyInto(out *AuditConfig) {
	*out = *in
	out.LogDestination = in.LogDestination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditConfig.
func (in *AuditConfig) DeepCopy() *AuditConfig {
	if in == nil {
		return nil
	}
	out := new(AuditConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRouteConfig) DeepCopyInto(out *AutoRouteConfig) {
	*out = *in
	out.ModelConfigRef = in.ModelConfigRef
	in.ClassificationPrompt.DeepCopyInto(&out.ClassificationPrompt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRouteConfig.
func (in *AutoRouteConfig) DeepCopy() *AutoRouteConfig {
	if in == nil {
		return nil
	}
	out := new(AutoRouteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockConfig) DeepCopyInto(out *BedrockConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockConfig.
func (in *BedrockConfig) DeepCopy() *BedrockConfig {
	if in == nil {
		return nil
	}
	out := new(BedrockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityRoute) DeepCopyInto(out *CapabilityRoute) {
	*out = *in
	out.AgentSpecRef = in.AgentSpecRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityRoute.
func (in *CapabilityRoute) DeepCopy() *CapabilityRoute {
	if in == nil {
		return nil
	}
	out := new(CapabilityRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelPlatform) DeepCopyInto(out *ChannelPlatform) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Telegram != nil {
		in, out := &in.Telegram, &out.Telegram
		*out = new(TelegramConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Discord != nil {
		in, out := &in.Discord, &out.Discord
		*out = new(DiscordConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = new(TeamsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelPlatform.
func (in *ChannelPlatform) DeepCopy() *ChannelPlatform {
	if in == nil {
		return nil
	}
	out := new(ChannelPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigFileSource) DeepCopyInto(out *ConfigFileSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigFileSource.
func (in *ConfigFileSource) DeepCopy() *ConfigFileSource {
	if in == nil {
		return nil
	}
	out := new(ConfigFileSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextRef) DeepCopyInto(out *ContextRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextRef.
func (in *ContextRef) DeepCopy() *ContextRef {
	if in == nil {
		return nil
	}
	out := new(ContextRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataClassificationConfig) DeepCopyInto(out *DataClassificationConfig) {
	*out = *in
	if in.AllowedLevels != nil {
		in, out := &in.AllowedLevels, &out.AllowedLevels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyPatterns != nil {
		in, out := &in.DenyPatterns, &out.DenyPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataClassificationConfig.
func (in *DataClassificationConfig) DeepCopy() *DataClassificationConfig {
	if in == nil {
		return nil
	}
	out := new(DataClassificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryConfig) DeepCopyInto(out *DeliveryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryConfig.
func (in *DeliveryConfig) DeepCopy() *DeliveryConfig {
	if in == nil {
		return nil
	}
	out := new(DeliveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscordConfig) DeepCopyInto(out *DiscordConfig) {
	*out = *in
	in.BotTokenSecret.DeepCopyInto(&out.BotTokenSecret)
	if in.AllowedRoleIDs != nil {
		in, out := &in.AllowedRoleIDs, &out.AllowedRoleIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscordConfig.
func (in *DiscordConfig) DeepCopy() *DiscordConfig {
	if in == nil {
		return nil
	}
	out := new(DiscordConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchPolicy) DeepCopyInto(out *DispatchPolicy) {
	*out = *in
	if in.DefaultTimeoutMinutes != nil {
		in, out := &in.DefaultTimeoutMinutes, &out.DefaultTimeoutMinutes
		*out = new(int32)
		**out = **in
	}
	out.RetryPolicy = in.RetryPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchPolicy.
func (in *DispatchPolicy) DeepCopy() *DispatchPolicy {
	if in == nil {
		return nil
	}
	out := new(DispatchPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dispatcher) DeepCopyInto(out *Dispatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dispatcher.
func (in *Dispatcher) DeepCopy() *Dispatcher {
	if in == nil {
		return nil
	}
	out := new(Dispatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dispatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatcherList) DeepCopyInto(out *DispatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dispatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatcherList.
func (in *DispatcherList) DeepCopy() *DispatcherList {
	if in == nil {
		return nil
	}
	out := new(DispatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DispatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatcherSpec) DeepCopyInto(out *DispatcherSpec) {
	*out = *in
	in.TaskGraphSelector.DeepCopyInto(&out.TaskGraphSelector)
	if in.CapabilityRoutes != nil {
		in, out := &in.CapabilityRoutes, &out.CapabilityRoutes
		*out = make([]CapabilityRoute, len(*in))
		copy(*out, *in)
	}
	if in.FallbackAgentSpecRef != nil {
		in, out := &in.FallbackAgentSpecRef, &out.FallbackAgentSpecRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	out.Messaging = in.Messaging
	if in.LLMRoute != nil {
		in, out := &in.LLMRoute, &out.LLMRoute
		*out = new(LLMRouteConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatcherSpec.
func (in *DispatcherSpec) DeepCopy() *DispatcherSpec {
	if in == nil {
		return nil
	}
	out := new(DispatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatcherStatus) DeepCopyInto(out *DispatcherStatus) {
	*out = *in
	if in.LastDispatchedAt != nil {
		in, out := &in.LastDispatchedAt, &out.LastDispatchedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatcherStatus.
func (in *DispatcherStatus) DeepCopy() *DispatcherStatus {
	if in == nil {
		return nil
	}
	out := new(DispatcherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationConfig) DeepCopyInto(out *EscalationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationConfig.
func (in *EscalationConfig) DeepCopy() *EscalationConfig {
	if in == nil {
		return nil
	}
	out := new(EscalationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalCase) DeepCopyInto(out *EvalCase) {
	*out = *in
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = make([]Assertion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalCase.
func (in *EvalCase) DeepCopy() *EvalCase {
	if in == nil {
		return nil
	}
	out := new(EvalCase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalGate) DeepCopyInto(out *EvalGate) {
	*out = *in
	out.EvalSuiteRef = in.EvalSuiteRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalGate.
func (in *EvalGate) DeepCopy() *EvalGate {
	if in == nil {
		return nil
	}
	out := new(EvalGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalResult) DeepCopyInto(out *EvalResult) {
	*out = *in
	in.EvaluatedAt.DeepCopyInto(&out.EvaluatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalResult.
func (in *EvalResult) DeepCopy() *EvalResult {
	if in == nil {
		return nil
	}
	out := new(EvalResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalSuite) DeepCopyInto(out *EvalSuite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalSuite.
func (in *EvalSuite) DeepCopy() *EvalSuite {
	if in == nil {
		return nil
	}
	out := new(EvalSuite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvalSuite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalSuiteList) DeepCopyInto(out *EvalSuiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvalSuite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalSuiteList.
func (in *EvalSuiteList) DeepCopy() *EvalSuiteList {
	if in == nil {
		return nil
	}
	out := new(EvalSuiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvalSuiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalSuiteSpec) DeepCopyInto(out *EvalSuiteSpec) {
	*out = *in
	out.AgentSpecRef = in.AgentSpecRef
	if in.EvalCases != nil {
		in, out := &in.EvalCases, &out.EvalCases
		*out = make([]EvalCase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalSuiteSpec.
func (in *EvalSuiteSpec) DeepCopy() *EvalSuiteSpec {
	if in == nil {
		return nil
	}
	out := new(EvalSuiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalSuiteStatus) DeepCopyInto(out *EvalSuiteStatus) {
	*out = *in
	if in.LastRunAt != nil {
		in, out := &in.LastRunAt, &out.LastRunAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalSuiteStatus.
func (in *EvalSuiteStatus) DeepCopy() *EvalSuiteStatus {
	if in == nil {
		return nil
	}
	out := new(EvalSuiteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSource) DeepCopyInto(out *EventSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSource.
func (in *EventSource) DeepCopy() *EventSource {
	if in == nil {
		return nil
	}
	out := new(EventSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemConfig) DeepCopyInto(out *FilesystemConfig) {
	*out = *in
	if in.AllowedMounts != nil {
		in, out := &in.AllowedMounts, &out.AllowedMounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemConfig.
func (in *FilesystemConfig) DeepCopy() *FilesystemConfig {
	if in == nil {
		return nil
	}
	out := new(FilesystemConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitCredential) DeepCopyInto(out *GitCredential) {
	*out = *in
	in.CredentialSecret.DeepCopyInto(&out.CredentialSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitCredential.
func (in *GitCredential) DeepCopy() *GitCredential {
	if in == nil {
		return nil
	}
	out := new(GitCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernationConfig) DeepCopyInto(out *HibernationConfig) {
	*out = *in
	out.IdleAfter = in.IdleAfter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernationConfig.
func (in *HibernationConfig) DeepCopy() *HibernationConfig {
	if in == nil {
		return nil
	}
	out := new(HibernationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboundConfig) DeepCopyInto(out *InboundConfig) {
	*out = *in
	out.DefaultTeamRef = in.DefaultTeamRef
	if in.TaskGraphTemplate != nil {
		in, out := &in.TaskGraphTemplate, &out.TaskGraphTemplate
		*out = new(TaskGraphTemplate)
		**out = **in
	}
	if in.AutoRoute != nil {
		in, out := &in.AutoRoute, &out.AutoRoute
		*out = new(AutoRouteConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboundConfig.
func (in *InboundConfig) DeepCopy() *InboundConfig {
	if in == nil {
		return nil
	}
	out := new(InboundConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMRouteConfig) DeepCopyInto(out *LLMRouteConfig) {
	*out = *in
	out.ModelConfigRef = in.ModelConfigRef
	if in.RoutingPromptRef != nil {
		in, out := &in.RoutingPromptRef, &out.RoutingPromptRef
		*out = new(SystemPromptConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMRouteConfig.
func (in *LLMRouteConfig) DeepCopy() *LLMRouteConfig {
	if in == nil {
		return nil
	}
	out := new(LLMRouteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogDestinationConfig) DeepCopyInto(out *LogDestinationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogDestinationConfig.
func (in *LogDestinationConfig) DeepCopy() *LogDestinationConfig {
	if in == nil {
		return nil
	}
	out := new(LogDestinationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoopEvalGate) DeepCopyInto(out *LoopEvalGate) {
	*out = *in
	out.EvalSuiteRef = in.EvalSuiteRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoopEvalGate.
func (in *LoopEvalGate) DeepCopy() *LoopEvalGate {
	if in == nil {
		return nil
	}
	out := new(LoopEvalGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoopGovernance) DeepCopyInto(out *LoopGovernance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoopGovernance.
func (in *LoopGovernance) DeepCopy() *LoopGovernance {
	if in == nil {
		return nil
	}
	out := new(LoopGovernance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoopTrigger) DeepCopyInto(out *LoopTrigger) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(EventSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoopTrigger.
func (in *LoopTrigger) DeepCopy() *LoopTrigger {
	if in == nil {
		return nil
	}
	out := new(LoopTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailboxMessage) DeepCopyInto(out *MailboxMessage) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailboxMessage.
func (in *MailboxMessage) DeepCopy() *MailboxMessage {
	if in == nil {
		return nil
	}
	out := new(MailboxMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mem0Config) DeepCopyInto(out *Mem0Config) {
	*out = *in
	in.APIKeySecret.DeepCopyInto(&out.APIKeySecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mem0Config.
func (in *Mem0Config) DeepCopy() *Mem0Config {
	if in == nil {
		return nil
	}
	out := new(Mem0Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryBackend) DeepCopyInto(out *MemoryBackend) {
	*out = *in
	if in.Mem0 != nil {
		in, out := &in.Mem0, &out.Mem0
		*out = new(Mem0Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryBackend.
func (in *MemoryBackend) DeepCopy() *MemoryBackend {
	if in == nil {
		return nil
	}
	out := new(MemoryBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStore) DeepCopyInto(out *MemoryStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStore.
func (in *MemoryStore) DeepCopy() *MemoryStore {
	if in == nil {
		return nil
	}
	out := new(MemoryStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemoryStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStoreList) DeepCopyInto(out *MemoryStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MemoryStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStoreList.
func (in *MemoryStoreList) DeepCopy() *MemoryStoreList {
	if in == nil {
		return nil
	}
	out := new(MemoryStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemoryStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStoreSpec) DeepCopyInto(out *MemoryStoreSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	if in.BoundAgents != nil {
		in, out := &in.BoundAgents, &out.BoundAgents
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStoreSpec.
func (in *MemoryStoreSpec) DeepCopy() *MemoryStoreSpec {
	if in == nil {
		return nil
	}
	out := new(MemoryStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStoreStatus) DeepCopyInto(out *MemoryStoreStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStoreStatus.
func (in *MemoryStoreStatus) DeepCopy() *MemoryStoreStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingConfig) DeepCopyInto(out *MessagingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingConfig.
func (in *MessagingConfig) DeepCopy() *MessagingConfig {
	if in == nil {
		return nil
	}
	out := new(MessagingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfig) DeepCopyInto(out *ModelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfig.
func (in *ModelConfig) DeepCopy() *ModelConfig {
	if in == nil {
		return nil
	}
	out := new(ModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigList) DeepCopyInto(out *ModelConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigList.
func (in *ModelConfigList) DeepCopy() *ModelConfigList {
	if in == nil {
		return nil
	}
	out := new(ModelConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigSpec) DeepCopyInto(out *ModelConfigSpec) {
	*out = *in
	if in.APIKeySecret != nil {
		in, out := &in.APIKeySecret, &out.APIKeySecret
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = new(BedrockConfig)
		**out = **in
	}
	if in.Vertex != nil {
		in, out := &in.Vertex, &out.Vertex
		*out = new(VertexConfig)
		**out = **in
	}
	out.Parameters = in.Parameters
	out.RateLimit = in.RateLimit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigSpec.
func (in *ModelConfigSpec) DeepCopy() *ModelConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ModelConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigStatus) DeepCopyInto(out *ModelConfigStatus) {
	*out = *in
	if in.LastValidatedAt != nil {
		in, out := &in.LastValidatedAt, &out.LastValidatedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigStatus.
func (in *ModelConfigStatus) DeepCopy() *ModelConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ModelConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConstraints) DeepCopyInto(out *ModelConstraints) {
	*out = *in
	if in.AllowedProviders != nil {
		in, out := &in.AllowedProviders, &out.AllowedProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedModels != nil {
		in, out := &in.DeniedModels, &out.DeniedModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConstraints.
func (in *ModelConstraints) DeepCopy() *ModelConstraints {
	if in == nil {
		return nil
	}
	out := new(ModelConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelParameters) DeepCopyInto(out *ModelParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelParameters.
func (in *ModelParameters) DeepCopy() *ModelParameters {
	if in == nil {
		return nil
	}
	out := new(ModelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRateLimit) DeepCopyInto(out *ModelRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRateLimit.
func (in *ModelRateLimit) DeepCopy() *ModelRateLimit {
	if in == nil {
		return nil
	}
	out := new(ModelRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundConfig) DeepCopyInto(out *OutboundConfig) {
	*out = *in
	if in.NotifyOn != nil {
		in, out := &in.NotifyOn, &out.NotifyOn
		*out = make([]ChannelEvent, len(*in))
		copy(*out, *in)
	}
	if in.SummaryModelConfigRef != nil {
		in, out := &in.SummaryModelConfigRef, &out.SummaryModelConfigRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundConfig.
func (in *OutboundConfig) DeepCopy() *OutboundConfig {
	if in == nil {
		return nil
	}
	out := new(OutboundConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeConfig) DeepCopyInto(out *RuntimeConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeConfig.
func (in *RuntimeConfig) DeepCopy() *RuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(RuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxClass) DeepCopyInto(out *SandboxClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxClass.
func (in *SandboxClass) DeepCopy() *SandboxClass {
	if in == nil {
		return nil
	}
	out := new(SandboxClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxClassList) DeepCopyInto(out *SandboxClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxClassList.
func (in *SandboxClassList) DeepCopy() *SandboxClassList {
	if in == nil {
		return nil
	}
	out := new(SandboxClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxClassSpec) DeepCopyInto(out *SandboxClassSpec) {
	*out = *in
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	in.Filesystem.DeepCopyInto(&out.Filesystem)
	if in.ResourceLimits != nil {
		in, out := &in.ResourceLimits, &out.ResourceLimits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.SecurityContext.DeepCopyInto(&out.SecurityContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxClassSpec.
func (in *SandboxClassSpec) DeepCopy() *SandboxClassSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxClassStatus) DeepCopyInto(out *SandboxClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxClassStatus.
func (in *SandboxClassStatus) DeepCopy() *SandboxClassStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxNetworkPolicy) DeepCopyInto(out *SandboxNetworkPolicy) {
	*out = *in
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxNetworkPolicy.
func (in *SandboxNetworkPolicy) DeepCopy() *SandboxNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(SandboxNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityContextConfig) DeepCopyInto(out *SecurityContextConfig) {
	*out = *in
	if in.RunAsUser != nil {
		in, out := &in.RunAsUser, &out.RunAsUser
		*out = new(int64)
		**out = **in
	}
	if in.SeccompProfile != nil {
		in, out := &in.SeccompProfile, &out.SeccompProfile
		*out = new(v1.SeccompProfile)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(v1.Capabilities)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityContextConfig.
func (in *SecurityContextConfig) DeepCopy() *SecurityContextConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityContextConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackConfig) DeepCopyInto(out *SlackConfig) {
	*out = *in
	in.AppCredentialSecret.DeepCopyInto(&out.AppCredentialSecret)
	in.SigningSecret.DeepCopyInto(&out.SigningSecret)
	if in.AppToken != nil {
		in, out := &in.AppToken, &out.AppToken
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedUserIDs != nil {
		in, out := &in.AllowedUserIDs, &out.AllowedUserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackConfig.
func (in *SlackConfig) DeepCopy() *SlackConfig {
	if in == nil {
		return nil
	}
	out := new(SlackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPromptConfig) DeepCopyInto(out *SystemPromptConfig) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPromptConfig.
func (in *SystemPromptConfig) DeepCopy() *SystemPromptConfig {
	if in == nil {
		return nil
	}
	out := new(SystemPromptConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	if in.Deps != nil {
		in, out := &in.Deps, &out.Deps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.AddedAt.DeepCopyInto(&out.AddedAt)
	if in.TimeoutMinutes != nil {
		in, out := &in.TimeoutMinutes, &out.TimeoutMinutes
		*out = new(int32)
		**out = **in
	}
	if in.AcceptanceCriteria != nil {
		in, out := &in.AcceptanceCriteria, &out.AcceptanceCriteria
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EvalGate != nil {
		in, out := &in.EvalGate, &out.EvalGate
		*out = new(EvalGate)
		**out = **in
	}
	if in.SandboxClassOverride != nil {
		in, out := &in.SandboxClassOverride, &out.SandboxClassOverride
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAssignedPayload) DeepCopyInto(out *TaskAssignedPayload) {
	*out = *in
	out.TaskGraphRef = in.TaskGraphRef
	if in.AcceptanceCriteria != nil {
		in, out := &in.AcceptanceCriteria, &out.AcceptanceCriteria
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContextRefs != nil {
		in, out := &in.ContextRefs, &out.ContextRefs
		*out = make([]ContextRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAssignedPayload.
func (in *TaskAssignedPayload) DeepCopy() *TaskAssignedPayload {
	if in == nil {
		return nil
	}
	out := new(TaskAssignedPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskGraph) DeepCopyInto(out *TaskGraph) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskGraph.
func (in *TaskGraph) DeepCopy() *TaskGraph {
	if in == nil {
		return nil
	}
	out := new(TaskGraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskGraph) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskGraphList) DeepCopyInto(out *TaskGraphList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskGraph, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskGraphList.
func (in *TaskGraphList) DeepCopy() *TaskGraphList {
	if in == nil {
		return nil
	}
	out := new(TaskGraphList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskGraphList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskGraphMutationPolicy) DeepCopyInto(out *TaskGraphMutationPolicy) {
	*out = *in
	if in.MutationScope != nil {
		in, out := &in.MutationScope, &out.MutationScope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyMutation != nil {
		in, out := &in.DenyMutation, &out.DenyMutation
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskGraphMutationPolicy.
func (in *TaskGraphMutationPolicy) DeepCopy() *TaskGraphMutationPolicy {
	if in == nil {
		return nil
	}
	out := new(TaskGraphMutationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskGraphSpec) DeepCopyInto(out *TaskGraphSpec) {
	*out = *in
	out.OwnerAgentRef = in.OwnerAgentRef
	out.DispatcherRef = in.DispatcherRef
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.DispatchPolicy.DeepCopyInto(&out.DispatchPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskGraphSpec.
func (in *TaskGraphSpec) DeepCopy() *TaskGraphSpec {
	if in == nil {
		return nil
	}
	out := new(TaskGraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskGraphStatus) DeepCopyInto(out *TaskGraphStatus) {
	*out = *in
	if in.LastDispatchedAt != nil {
		in, out := &in.LastDispatchedAt, &out.LastDispatchedAt
		*out = (*in).DeepCopy()
	}
	if in.TaskStatuses != nil {
		in, out := &in.TaskStatuses, &out.TaskStatuses
		*out = make(map[string]TaskRuntimeState, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskGraphStatus.
func (in *TaskGraphStatus) DeepCopy() *TaskGraphStatus {
	if in == nil {
		return nil
	}
	out := new(TaskGraphStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskGraphTemplate) DeepCopyInto(out *TaskGraphTemplate) {
	*out = *in
	out.OwnerAgentRef = in.OwnerAgentRef
	out.DispatcherRef = in.DispatcherRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskGraphTemplate.
func (in *TaskGraphTemplate) DeepCopy() *TaskGraphTemplate {
	if in == nil {
		return nil
	}
	out := new(TaskGraphTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRef) DeepCopyInto(out *TaskRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRef.
func (in *TaskRef) DeepCopy() *TaskRef {
	if in == nil {
		return nil
	}
	out := new(TaskRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRuntimeState) DeepCopyInto(out *TaskRuntimeState) {
	*out = *in
	if in.AssignedAt != nil {
		in, out := &in.AssignedAt, &out.AssignedAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.EvalResult != nil {
		in, out := &in.EvalResult, &out.EvalResult
		*out = new(EvalResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRuntimeState.
func (in *TaskRuntimeState) DeepCopy() *TaskRuntimeState {
	if in == nil {
		return nil
	}
	out := new(TaskRuntimeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamHandoffRule) DeepCopyInto(out *TeamHandoffRule) {
	*out = *in
	out.FromTeamRef = in.FromTeamRef
	out.ToTeamRef = in.ToTeamRef
	if in.HandoffTaskGraphTemplate != nil {
		in, out := &in.HandoffTaskGraphTemplate, &out.HandoffTaskGraphTemplate
		*out = new(TaskGraphTemplate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamHandoffRule.
func (in *TeamHandoffRule) DeepCopy() *TeamHandoffRule {
	if in == nil {
		return nil
	}
	out := new(TeamHandoffRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSharedResources) DeepCopyInto(out *TeamSharedResources) {
	*out = *in
	if in.MemoryRef != nil {
		in, out := &in.MemoryRef, &out.MemoryRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ToolSetRef != nil {
		in, out := &in.ToolSetRef, &out.ToolSetRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.SandboxClassRef != nil {
		in, out := &in.SandboxClassRef, &out.SandboxClassRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ModelConfigRef != nil {
		in, out := &in.ModelConfigRef, &out.ModelConfigRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSharedResources.
func (in *TeamSharedResources) DeepCopy() *TeamSharedResources {
	if in == nil {
		return nil
	}
	out := new(TeamSharedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamsConfig) DeepCopyInto(out *TeamsConfig) {
	*out = *in
	in.AppCredentialSecret.DeepCopyInto(&out.AppCredentialSecret)
	if in.AllowedUserIDs != nil {
		in, out := &in.AllowedUserIDs, &out.AllowedUserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamsConfig.
func (in *TeamsConfig) DeepCopy() *TeamsConfig {
	if in == nil {
		return nil
	}
	out := new(TeamsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegramConfig) DeepCopyInto(out *TelegramConfig) {
	*out = *in
	in.BotTokenSecret.DeepCopyInto(&out.BotTokenSecret)
	if in.AllowedUserIDs != nil {
		in, out := &in.AllowedUserIDs, &out.AllowedUserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegramConfig.
func (in *TelegramConfig) DeepCopy() *TelegramConfig {
	if in == nil {
		return nil
	}
	out := new(TelegramConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolCallGovernance) DeepCopyInto(out *ToolCallGovernance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolCallGovernance.
func (in *ToolCallGovernance) DeepCopy() *ToolCallGovernance {
	if in == nil {
		return nil
	}
	out := new(ToolCallGovernance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolEntry) DeepCopyInto(out *ToolEntry) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CredentialSecret != nil {
		in, out := &in.CredentialSecret, &out.CredentialSecret
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolEntry.
func (in *ToolEntry) DeepCopy() *ToolEntry {
	if in == nil {
		return nil
	}
	out := new(ToolEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSet) DeepCopyInto(out *ToolSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSet.
func (in *ToolSet) DeepCopy() *ToolSet {
	if in == nil {
		return nil
	}
	out := new(ToolSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSetList) DeepCopyInto(out *ToolSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ToolSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSetList.
func (in *ToolSetList) DeepCopy() *ToolSetList {
	if in == nil {
		return nil
	}
	out := new(ToolSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSetSpec) DeepCopyInto(out *ToolSetSpec) {
	*out = *in
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSetSpec.
func (in *ToolSetSpec) DeepCopy() *ToolSetSpec {
	if in == nil {
		return nil
	}
	out := new(ToolSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSetStatus) DeepCopyInto(out *ToolSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSetStatus.
func (in *ToolSetStatus) DeepCopy() *ToolSetStatus {
	if in == nil {
		return nil
	}
	out := new(ToolSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VertexConfig) DeepCopyInto(out *VertexConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VertexConfig.
func (in *VertexConfig) DeepCopy() *VertexConfig {
	if in == nil {
		return nil
	}
	out := new(VertexConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	if in.AuthSecret != nil {
		in, out := &in.AuthSecret, &out.AuthSecret
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceCredentialsConfig) DeepCopyInto(out *WorkspaceCredentialsConfig) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = make([]GitCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceCredentialsConfig.
func (in *WorkspaceCredentialsConfig) DeepCopy() *WorkspaceCredentialsConfig {
	if in == nil {
		return nil
	}
	out := new(WorkspaceCredentialsConfig)
	in.DeepCopyInto(out)
	return out
}
