#!/bin/bash
set -euo pipefail

# Generates a Goose config.yaml from KARO environment variables.
# The AgentInstance controller injects these env vars from the ModelConfig:
#   KARO_MODEL_PROVIDER  - e.g., anthropic, openai, ollama, bedrock, vertex-ai
#   KARO_MODEL_NAME      - e.g., claude-sonnet-4-20250514, gpt-4o
#   KARO_MODEL_API_KEY   - API key (from Secret reference)
#   KARO_API_BASE_URL    - Custom API base URL (optional)
#   KARO_TEMPERATURE     - Temperature setting (optional)
#   KARO_MAX_TOKENS      - Max tokens (optional)

PROVIDER="${KARO_MODEL_PROVIDER:-anthropic}"
MODEL="${KARO_MODEL_NAME:-claude-sonnet-4-20250514}"

# Map KARO ModelConfig provider names to Goose provider names
case "$PROVIDER" in
  anthropic)
    GOOSE_PROVIDER="anthropic"
    ;;
  openai)
    GOOSE_PROVIDER="openai"
    ;;
  bedrock|aws-bedrock)
    GOOSE_PROVIDER="aws-bedrock"
    ;;
  vertex-ai|vertex|google-vertex)
    GOOSE_PROVIDER="google-vertex"
    ;;
  ollama)
    GOOSE_PROVIDER="ollama"
    ;;
  azure-openai|azure)
    GOOSE_PROVIDER="azure-openai"
    ;;
  *)
    GOOSE_PROVIDER="$PROVIDER"
    ;;
esac

cat <<EOF
# Auto-generated by karo-generate-goose-config
# Provider: ${PROVIDER} -> Goose provider: ${GOOSE_PROVIDER}
# Model: ${MODEL}

provider: ${GOOSE_PROVIDER}
model: ${MODEL}
EOF

# Add optional settings
if [ -n "${KARO_TEMPERATURE:-}" ]; then
  echo "temperature: ${KARO_TEMPERATURE}"
fi

if [ -n "${KARO_MAX_TOKENS:-}" ]; then
  echo "max_tokens: ${KARO_MAX_TOKENS}"
fi

if [ -n "${KARO_API_BASE_URL:-}" ]; then
  echo "api_base: ${KARO_API_BASE_URL}"
fi

# Context management settings
cat <<EOF

# Context management
context_strategy: ${GOOSE_CONTEXT_STRATEGY:-summarize}
EOF
